site_name: MCG脚本教程
theme:
  name: material
  features:
    - navigation.footer
    - navigation.indexes
repo_url: https://github.com/MineCraftGensoukyo/Tutorial

nav:
  - 前言: index.md
  - 搭建环境:
    - 编写环境: build-enviroment/edit-enviroment.md
    - 运行环境: build-enviroment/running-enviroment.md